### ISSUE TITLE
Add API to get stats by gem name

### ISSUE THREAD

**Issue by prokopsimek** [ossert/ossert#21]

**Comment by sclinede** [comment]
@prokopsimek Hey, sorry for so long delay. 
Could you please share the use-case or scenario which you want to try with the API?
What exactly do you expect from the API?

You know, API could lead to a heavy load and I have to find a good reason for the implementation.

I want to cleanup the Issues so if we'll find an interesting case we could ship whatever you want.
Otherwise, I'll prefer to close it for now. Unless we find pragmatic reason for it.

**Comment by sclinede** [comment]
I'm closing this for now. But if anyone will be interested in API and will provide any use-case or workflow we'll continue with it.
